# 项目相关配置
szhbl:
  # 名称
  name: szhbl
  # 版本
  version: 2.0.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/szhbl/uploadPath，Linux配置 /home/szhbl/uploadPath）
  profile: E:/szhbl/uploadPath
  # 获取ip地址开关
  addressEnabled: true
  # 服务器地址
  serverHost: 117.159.3.248

  fileServer: http://117.159.3.248:8083

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8083
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
    accesslog:
      buffered: true
      directory: D:/booking_platform_tomcat
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: wangzhichao
#    key-store-type: PKCS12
#    key-alias: tomcat

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 1200

# 七牛云服务器配置信息-华东区
upload:
  qiniu:
    # 域名
    domain: q2suk6pem.bkt.clouddn.com
    # AK
    accessKey: pN0buVMmYrfb2v2M4Wrdat7oQTGcyIPJRM1b2G4o
    # SK
    secretKey: 3lmNBlFeoKRFJUoNMdImmVM2zF0bM46Cx77aFak9
    # 空间名
    bucket: wang-space-001

#info:
#  app:
#    name: spring-boot-actuator
#    version: 1.0.0
#    test: test
# 数据源配置
spring:
  redis:
    host: 117.159.3.248
    password: banlietest123
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  #  boot:
  #    admin:
  #      client:
  #        url: http://117.159.3.248:8081
  rabbitmq:
    host: 117.159.3.248
    username: mquser
    password: banlietest
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true
      direct:
        acknowledge-mode: manual
  mail:
    host: smtp.qiye.163.com #发送邮件服务器
    username: booking@zih718.com #发送邮件的邮箱地址
    password: UD6VqLfJRq2yhDwJ #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties:
      mail:
        smtp:
          port: 994 #465或者994
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    from: booking@zih718.com # 发送邮件的地址，和上面username一致 可以任意s
    default-encoding: utf-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://117.159.3.234:3306/booking_platform_system_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: szhbl
        password: Szhbl@20200106
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 30
      # 配置获取连接等待超时的时间
      maxWait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

